### ISSUE TITLE
副屏向主屏发送数据报错

### ISSUE THREAD

**Issue by w463022633** [liyufengrex/flutter_subscreen_plugin#1]
```
E/MethodChannel#screen_plugin_main_channel( 1768): Failed to handle method call
E/MethodChannel#screen_plugin_main_channel( 1768): kotlin.UninitializedPropertyAccessException: lateinit property subChannel has not been initialized
E/MethodChannel#screen_plugin_main_channel( 1768):      at com.rex.flutter_subscreen_plugin.FlutterSubscreenPlugin.onMethodCall(FlutterSubscreenPlugin.kt:45)
E/MethodChannel#screen_plugin_main_channel( 1768):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#screen_plugin_main_channel( 1768):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#screen_plugin_main_channel( 1768):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#screen_plugin_main_channel( 1768):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#screen_plugin_main_channel( 1768):      at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#screen_plugin_main_channel( 1768):      at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#screen_plugin_main_channel( 1768):      at android.app.ActivityThread.main(ActivityThread.java:6141)
E/MethodChannel#screen_plugin_main_channel( 1768):      at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#screen_plugin_main_channel( 1768):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/MethodChannel#screen_plugin_main_channel( 1768):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by w463022633** [comment]
示例代码调用方法写错了，解决了。
