### ISSUE TITLE
开启副屏幕报错 

### ISSUE THREAD

**Issue by shs8023you** [liyufengrex/flutter_subscreen_plugin#14]
I/System.out(13560): Unable to add window android.view.ViewRootImpl$W@40cd4ee -- the specified window type 2038 is not valid
W/System.err(13560): android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@40cd4ee -- the specified window type 2038 is not valid
W/System.err(13560): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1632)
W/System.err(13560): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:509)
W/System.err(13560): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
W/System.err(13560): 	at android.app.Dialog.show(Dialog.java:512)
W/System.err(13560): 	at android.app.Presentation.show(Presentation.java:305)
W/System.err(13560): 	at com.rex.flutter_subscreen_plugin.FlutterSubScreenPresentation.show(FlutterSubScreenPresentation.kt:36)
W/System.err(13560): 	at com.rex.flutter_subscreen_plugin.FlutterSubScreenProvider.configSecondDisplay(FlutterSubScreenProvider.kt:201)
W/System.err(13560): 	at com.rex.flutter_subscreen_plugin.FlutterSubScreenProvider.showSubDisplay(FlutterSubScreenProvider.kt:154)
W/System.err(13560): 	at com.rex.flutter_subscreen_plugin.FlutterSubscreenPlugin.onMethodCall(FlutterSubscreenPlugin.kt:72)
W/System.err(13560): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(13560): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(13560): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(13560): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(13560): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(13560): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(13560): 	at android.os.Looper.loopOnce(Looper.java:226)
W/System.err(13560): 	at android.os.Looper.loop(Looper.java:313)
W/System.err(13560): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
W/System.err(13560): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(13560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
W/System.err(13560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by yx-design** [comment]
这个是什么问题？

**Comment by liyufengrex** [comment]
> 这个是什么问题？

是不是开启副屏前没有判断overlay权限是否开启
