### ISSUE TITLE
退出之后会报以下的错误

### ISSUE THREAD

**Issue by 550655294** [liyufengrex/flutter_subscreen_plugin#15]
android.view.WindowLeaked: Activity com.example.bq_cashier.MainActivity has leaked window DecorView@1db110a[] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                                                                                                    	at android.app.Dialog.show(Dialog.java:322)
                                                                                                    	at android.app.Presentation.show(Presentation.java:235)
                                                                                                    	at com.rex.flutter_subscreen_plugin.FlutterSubScreenPresentation.show(FlutterSubScreenPresentation.kt:36)
                                                                                                    	at com.rex.flutter_subscreen_plugin.FlutterSubScreenProvider.configSecondDisplay(FlutterSubScreenProvider.kt:201)
                                                                                                    	at com.rex.flutter_subscreen_plugin.FlutterSubScreenProvider.showSubDisplay(FlutterSubScreenProvider.kt:154)
                                                                                                    	at com.rex.flutter_subscreen_plugin.FlutterSubScreenProvider.doInit(FlutterSubScreenProvider.kt:81)
                                                                                                    	at com.rex.flutter_subscreen_plugin.FlutterSubscreenPlugin.onAttachedToActivity(FlutterSubscreenPlugin.kt:103)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:156)
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:39)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1277)
                                                                                                    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:213)
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:634)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:6735)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                                    	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

这是我在点击返回键之后 报的错误 貌似是退出之后再次执行了一次注册导致的问题 这会导致退出app但是后台在不杀进程的情况下，再次进入app无法显示副屏

**Comment by liyufengrex** [comment]
@550655294 你好，现象按照你的步骤我复现了，但是报错不一样，现已修复，你可以用最新版本 1.2.0 再试试

**Comment by 550655294** [comment]
> @550655294 你好，现象按照你的步骤我复现了，但是报错不一样，现已修复，你可以用最新版本 1.2.0 再试试

谢谢 我试一下
