### ISSUE TITLE
新版本有BUG，无法正常通信

### ISSUE THREAD

**Issue by cwangfr** [liyufengrex/flutter_subscreen_plugin#9]
新版本在初始化后与副屏通信时会出现异常，无法正常通信

异常如下
E/flutter (13988): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, lateinit property subChannel has not been initialized, null, b4.s: lateinit property subChannel has not been initialized
E/flutter (13988): 	at r2.d.onMethodCall(FlutterSubscreenPlugin.kt:14)
E/flutter (13988): 	at r3.k$a.a(MethodChannel.java:2)
E/flutter (13988): 	at e3.c.l(DartMessenger.java:2)
E/flutter (13988): 	at e3.c.m(DartMessenger.java:2)
E/flutter (13988): 	at e3.c.i(Unknown Source:0)
E/flutter (13988): 	at e3.b.run(Unknown Source:12)
E/flutter (13988): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (13988): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (13988): 	at android.os.Looper.loop(Looper.java:223)
E/flutter (13988): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/flutter (13988): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13988): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (13988): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (13988): )
E/flutter (13988): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
E/flutter (13988): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter (13988): <asynchronous suspension>
E/flutter (13988): #2      SubScreenPlugin.sendMsgToViceScreen (package:flutter_subscreen_plugin/src/sub_screen_plugin.dart:80)
E/flutter (13988): <asynchronous suspension>
E/flutter (13988): 

这个问题从1.0.6开始出现

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.22621.963], locale zh-CN)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by liyufengrex** [comment]
感谢反馈，1.0.8已修复
